### ISSUE TITLE
FR: Provide an efficient way to resolve icon out of composition

### ISSUE THREAD

**Issue by Nek-12** [tclement0922/compose-font-icons#4]
Here's currently the hacky way we use to load fonts into bitmaps on Android:

```
// TODO: This is a huge hack to get access to compose resources outside of composition and may break at any moment
//    Relies on compose 1.7.0 asset resource handling logic internals

val resourceUri = Res.getUri("font/fontawesome_font_v6.ttf")

val String.assetPath: String
    get() = Uri.parse(this)
        .path
        .orEmpty()
        .removePrefix("/android_asset/")

private val font = Font(path = resourceUri, assets)

fun FontResourceIcon(font: Font, context: Context, icon: Char, color: Color = Color.White): Bitmap {
    return FontIconBitmap(icon, context, color, StaticIconFont(arrayOf(font), "liga"))
}
```

This is very fragile, cumbersome, unsafe and non-performant and also uses internal library APIs with the need to suppress the error.
There should be a way to take a compose resource identifier for a font and return an icon bitmap out of the box. 

Our use-case is that we draw font icons in notifications depending on the icon name which comes from the database, for example in the status bar we draw an icon the user chose, which requires passing either Android's Bitmap, Icon or Drawable to the NotificationCompat's constructor. We also do this in a non-suspending context on main thread - the Service event loop.

And ideal solution would be to have:

```
fun FontIconBitmap(name: String, font: FontResource, context: Context, tint: Color? = null): Bitmap
```

P.S. For the issue in TODO we may need to file a bug on YouTrack because I searched and haven't found any.

**Comment by tclement0922** [comment]
This is a limitation of the compose resources library, unless the other `Font` functions, the one from compose resources is annotated with `Composable`.

Something like this should work:
```kotlin
@OptIn(ExperimentalResourceApi::class)
public fun createStaticIconFont(
    context: Context,
    fontResource: FontResource,
    fontFeatureSettings: String? = null
): IconFont {
    val environment = getSystemResourceEnvironment()
    val bytes = runBlocking {
        getFontResourceBytes(environment, fontResource)
    }
    val file = context.cacheDir.resolve(bytes.contentHashCode().toString())
    if (!file.exists()) {
        file.writeBytes(bytes)
    }
    return StaticIconFont(
        fonts = arrayOf(Font(file = file)),
        featureSettings = fontFeatureSettings
    )
}
```
I used the same kind of workaround for variable fonts on Android. This is not perfect because it requires copying the font from the assets to the cache, but at least it doesn't depends on the internal logic of the resources library.

**Comment by Nek-12** [comment]
That function will definitely not work for us, not only it does I/O on the main thread, but also I do not see any point in creating a separate file for the font when the exact same file is already in the assets directory. Our problem is that the `StaticIconFont` constructor is internal and that the logic for resolving the font from system assets is exposed to client code.

**Comment by tclement0922** [comment]
As I said this far from being perfect, but this is the only workaround I found to avoid relying on internal logic. It would be way better if I could just create a typeface from a byte array like I do on Skiko, but unfortunately Android doesn't seem to support that. I'll try to look more deeply into better alternatives to do this but I can't promise any result.

**Comment by Nek-12** [comment]
https://youtrack.jetbrains.com/issue/CMP-5917/

**Comment by tclement0922** [comment]
I agree with the JetBrains team member that answered your issue, compose multiplatform resources are not designed to be used outside of compose, and my library is not supposed to either.

`FontIconBitmap` was originally only for usage in AndroidX Glance where everything happens in a composable, and I didn't think about the fact that someone would need to create a FontIcon outside the composition.

I think I'll just add 2 non composable functions `createStaticIconFont` and `createVariableIconFont` that will simply take one or multiple `Font` as parameters (plus the common ones like `fontFeatureSettings`). This will fix the part of your issue regarding the visibility of `StaticIconFont`.

**Comment by Nek-12** [comment]
The problem is that I do not understand how my use case could be achieved without that. I added a comment on YT explaining the situation. Do you have any solutions in mind?

**Comment by tclement0922** [comment]
Well it's not a perfect solution since it won't support the `Res.font.font_name` format, but the idea I proposed earlier would work :

> 2 non composable functions createStaticIconFont and createVariableIconFont that will simply take one or multiple Font as parameters (plus the common ones like fontFeatureSettings).

This would transform your very first example to:
```kotlin
val fontPath = Res.getUri("font/fontawesome_font_v6.ttf").removePrefix("/android_asset/")
val iconFont = createStaticIconFont(Font(path = fontPath, assets), "liga")

fun FontResourceIcon(font: Font, context: Context, icon: Char, color: Color = Color.White): Bitmap {
    return FontIconBitmap(icon, context, color, iconFont)
}
```
This would obviously be better if the compose resources library had a way to get resource path from a resource ID, outside of composition.
However I understand the point of view of the JetBrains devs, compose resources is a compose multiplatform library, there is no reason to add things that would make it work outside of composition. The best solution for that would be an actual KMP resources library that supports every target of Kotlin, unlike compose multiplatform which only supports a subset of those targets.

**Comment by Nek-12** [comment]
Yes your solution would work perfectly, when that is done we can close the issue. On the topic of responsibilities, I believe there is no such thing as "compose only resources". Like in our case, resources can be shared by a lot of places in the code, but duplicating them has a lot more impact than duplicating code. Here, we would for example need an entire separate library (like iconics to render icons via xml) and a full duplicate of the font file. Not acceptable for us given that the font constitutes 15% of the apk size.
